# Generated by Django 3.0.5 on 2020-04-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.TextField(default='BOOM', max_length=4),
        ),
    ]
